:- module(
  iso_639_2,
  [
    language/2 % ?ISO:atom
               % ?Lexvo:uri
  ]
').

/** <module> ISO 639-2

The ISO 639-2 standard for language codes with Lexvo Semantic Web URIs.

!!iso_639_2!!language!!2!!

WWW: [http://www.sil.org/iso639-2/]

@author Wouter Beek
@version 2013/01
*/



%% language(?ISO:atom, ?Lexvo:uri) is nondet.

language(aar, 'http://lexvo.org/id/iso639-3/aar').
language(abk, 'http://lexvo.org/id/iso639-3/abk').
language(ace, 'http://lexvo.org/id/iso639-3/ace').
language(ach, 'http://lexvo.org/id/iso639-3/ach').
language(ada, 'http://lexvo.org/id/iso639-3/ada').
language(ady, 'http://lexvo.org/id/iso639-3/ady').
language(afa, 'http://lexvo.org/id/iso639-5/afa').
language(afh, 'http://lexvo.org/id/iso639-3/afh').
language(afr, 'http://lexvo.org/id/iso639-3/afr').
language(ain, 'http://lexvo.org/id/iso639-3/ain').
language(aka, 'http://lexvo.org/id/iso639-3/aka').
language(akk, 'http://lexvo.org/id/iso639-3/akk').
language(alb, 'http://lexvo.org/id/iso639-3/sqi').
language(ale, 'http://lexvo.org/id/iso639-3/ale').
language(alg, 'http://lexvo.org/id/iso639-5/alg').
language(alt, 'http://lexvo.org/id/iso639-3/alt').
language(amh, 'http://lexvo.org/id/iso639-3/amh').
language(ang, 'http://lexvo.org/id/iso639-3/ang').
language(anp, 'http://lexvo.org/id/iso639-3/anp').
language(apa, 'http://lexvo.org/id/iso639-5/apa').
language(ara, 'http://lexvo.org/id/iso639-3/ara').
language(arc, 'http://lexvo.org/id/iso639-3/arc').
language(arg, 'http://lexvo.org/id/iso639-3/arg').
language(arm, 'http://lexvo.org/id/iso639-3/hye').
language(arn, 'http://lexvo.org/id/iso639-3/arn').
language(arp, 'http://lexvo.org/id/iso639-3/arp').
language(art, 'http://lexvo.org/id/iso639-5/art').
language(arw, 'http://lexvo.org/id/iso639-3/arw').
language(asm, 'http://lexvo.org/id/iso639-3/asm').
language(ast, 'http://lexvo.org/id/iso639-3/ast').
language(ath, 'http://lexvo.org/id/iso639-5/ath').
language(aus, 'http://lexvo.org/id/iso639-5/aus').
language(ava, 'http://lexvo.org/id/iso639-3/ava').
language(ave, 'http://lexvo.org/id/iso639-3/ave').
language(awa, 'http://lexvo.org/id/iso639-3/awa').
language(aym, 'http://lexvo.org/id/iso639-3/aym').
language(aze, 'http://lexvo.org/id/iso639-3/aze').
language(bad, 'http://lexvo.org/id/iso639-5/bad').
language(bai, 'http://lexvo.org/id/iso639-5/bai').
language(bak, 'http://lexvo.org/id/iso639-3/bak').
language(bal, 'http://lexvo.org/id/iso639-3/bal').
language(bam, 'http://lexvo.org/id/iso639-3/bam').
language(ban, 'http://lexvo.org/id/iso639-3/ban').
language(baq, 'http://lexvo.org/id/iso639-3/eus').
language(bas, 'http://lexvo.org/id/iso639-3/bas').
language(bat, 'http://lexvo.org/id/iso639-5/bat').
language(bej, 'http://lexvo.org/id/iso639-3/bej').
language(bel, 'http://lexvo.org/id/iso639-3/bel').
language(bem, 'http://lexvo.org/id/iso639-3/bem').
language(ben, 'http://lexvo.org/id/iso639-3/ben').
language(ber, 'http://lexvo.org/id/iso639-5/ber').
language(bho, 'http://lexvo.org/id/iso639-3/bho').
language(bik, 'http://lexvo.org/id/iso639-3/bik').
language(bin, 'http://lexvo.org/id/iso639-3/bin').
language(bis, 'http://lexvo.org/id/iso639-3/bis').
language(bla, 'http://lexvo.org/id/iso639-3/bla').
language(bnt, 'http://lexvo.org/id/iso639-5/bnt').
language(bod, 'http://lexvo.org/id/iso639-3/bod').
language(bos, 'http://lexvo.org/id/iso639-3/bos').
language(bra, 'http://lexvo.org/id/iso639-3/bra').
language(bre, 'http://lexvo.org/id/iso639-3/bre').
language(btk, 'http://lexvo.org/id/iso639-5/btk').
language(bua, 'http://lexvo.org/id/iso639-3/bua').
language(bug, 'http://lexvo.org/id/iso639-3/bug').
language(bul, 'http://lexvo.org/id/iso639-3/bul').
language(bur, 'http://lexvo.org/id/iso639-3/mya').
language(byn, 'http://lexvo.org/id/iso639-3/byn').
language(cad, 'http://lexvo.org/id/iso639-3/cad').
language(cai, 'http://lexvo.org/id/iso639-5/cai').
language(car, 'http://lexvo.org/id/iso639-3/car').
language(cat, 'http://lexvo.org/id/iso639-3/cat').
language(cau, 'http://lexvo.org/id/iso639-5/cau').
language(ceb, 'http://lexvo.org/id/iso639-3/ceb').
language(cel, 'http://lexvo.org/id/iso639-5/cel').
language(ces, 'http://lexvo.org/id/iso639-3/ces').
language(cha, 'http://lexvo.org/id/iso639-3/cha').
language(chb, 'http://lexvo.org/id/iso639-3/chb').
language(che, 'http://lexvo.org/id/iso639-3/che').
language(chg, 'http://lexvo.org/id/iso639-3/chg').
language(chi, 'http://lexvo.org/id/iso639-3/zho').
language(chk, 'http://lexvo.org/id/iso639-3/chk').
language(chm, 'http://lexvo.org/id/iso639-3/chm').
language(chn, 'http://lexvo.org/id/iso639-3/chn').
language(cho, 'http://lexvo.org/id/iso639-3/cho').
language(chp, 'http://lexvo.org/id/iso639-3/chp').
language(chr, 'http://lexvo.org/id/iso639-3/chr').
language(chu, 'http://lexvo.org/id/iso639-3/chu').
language(chv, 'http://lexvo.org/id/iso639-3/chv').
language(chy, 'http://lexvo.org/id/iso639-3/chy').
language(cmc, 'http://lexvo.org/id/iso639-5/cmc').
language(cop, 'http://lexvo.org/id/iso639-3/cop').
language(cor, 'http://lexvo.org/id/iso639-3/cor').
language(cos, 'http://lexvo.org/id/iso639-3/cos').
language(cpe, 'http://lexvo.org/id/iso639-5/cpe').
language(cpf, 'http://lexvo.org/id/iso639-5/cpf').
language(cpp, 'http://lexvo.org/id/iso639-5/cpp').
language(cre, 'http://lexvo.org/id/iso639-3/cre').
language(crh, 'http://lexvo.org/id/iso639-3/crh').
language(crp, 'http://lexvo.org/id/iso639-5/crp').
language(csb, 'http://lexvo.org/id/iso639-3/csb').
language(cus, 'http://lexvo.org/id/iso639-5/cus').
language(cym, 'http://lexvo.org/id/iso639-3/cym').
language(cze, 'http://lexvo.org/id/iso639-3/ces').
language(dak, 'http://lexvo.org/id/iso639-3/dak').
language(dan, 'http://lexvo.org/id/iso639-3/dan').
language(dar, 'http://lexvo.org/id/iso639-3/dar').
language(day, 'http://lexvo.org/id/iso639-5/day').
language(del, 'http://lexvo.org/id/iso639-3/del').
language(den, 'http://lexvo.org/id/iso639-3/den').
language(deu, 'http://lexvo.org/id/iso639-3/deu').
language(dgr, 'http://lexvo.org/id/iso639-3/dgr').
language(din, 'http://lexvo.org/id/iso639-3/din').
language(div, 'http://lexvo.org/id/iso639-3/div').
language(doi, 'http://lexvo.org/id/iso639-3/doi').
language(dra, 'http://lexvo.org/id/iso639-5/dra').
language(dsb, 'http://lexvo.org/id/iso639-3/dsb').
language(dua, 'http://lexvo.org/id/iso639-3/dua').
language(dum, 'http://lexvo.org/id/iso639-3/dum').
language(dut, 'http://lexvo.org/id/iso639-3/nld').
language(dyu, 'http://lexvo.org/id/iso639-3/dyu').
language(dzo, 'http://lexvo.org/id/iso639-3/dzo').
language(efi, 'http://lexvo.org/id/iso639-3/efi').
language(egy, 'http://lexvo.org/id/iso639-3/egy').
language(eka, 'http://lexvo.org/id/iso639-3/eka').
language(ell, 'http://lexvo.org/id/iso639-3/ell').
language(elx, 'http://lexvo.org/id/iso639-3/elx').
language(eng, 'http://lexvo.org/id/iso639-3/eng').
language(enm, 'http://lexvo.org/id/iso639-3/enm').
language(epo, 'http://lexvo.org/id/iso639-3/epo').
language(est, 'http://lexvo.org/id/iso639-3/est').
language(eus, 'http://lexvo.org/id/iso639-3/eus').
language(ewe, 'http://lexvo.org/id/iso639-3/ewe').
language(ewo, 'http://lexvo.org/id/iso639-3/ewo').
language(fan, 'http://lexvo.org/id/iso639-3/fan').
language(fao, 'http://lexvo.org/id/iso639-3/fao').
language(fas, 'http://lexvo.org/id/iso639-3/fas').
language(fat, 'http://lexvo.org/id/iso639-3/fat').
language(fij, 'http://lexvo.org/id/iso639-3/fij').
language(fil, 'http://lexvo.org/id/iso639-3/fil').
language(fin, 'http://lexvo.org/id/iso639-3/fin').
language(fiu, 'http://lexvo.org/id/iso639-5/fiu').
language(fon, 'http://lexvo.org/id/iso639-3/fon').
language(fra, 'http://lexvo.org/id/iso639-3/fra').
language(fre, 'http://lexvo.org/id/iso639-3/fra').
language(frm, 'http://lexvo.org/id/iso639-3/frm').
language(fro, 'http://lexvo.org/id/iso639-3/fro').
language(frr, 'http://lexvo.org/id/iso639-3/frr').
language(frs, 'http://lexvo.org/id/iso639-3/frs').
language(fry, 'http://lexvo.org/id/iso639-3/fry').
language(ful, 'http://lexvo.org/id/iso639-3/ful').
language(fur, 'http://lexvo.org/id/iso639-3/fur').
language(gaa, 'http://lexvo.org/id/iso639-3/gaa').
language(gay, 'http://lexvo.org/id/iso639-3/gay').
language(gba, 'http://lexvo.org/id/iso639-3/gba').
language(gem, 'http://lexvo.org/id/iso639-5/gem').
language(geo, 'http://lexvo.org/id/iso639-3/kat').
language(ger, 'http://lexvo.org/id/iso639-3/deu').
language(gez, 'http://lexvo.org/id/iso639-3/gez').
language(gil, 'http://lexvo.org/id/iso639-3/gil').
language(gla, 'http://lexvo.org/id/iso639-3/gla').
language(gle, 'http://lexvo.org/id/iso639-3/gle').
language(glg, 'http://lexvo.org/id/iso639-3/glg').
language(glv, 'http://lexvo.org/id/iso639-3/glv').
language(gmh, 'http://lexvo.org/id/iso639-3/gmh').
language(goh, 'http://lexvo.org/id/iso639-3/goh').
language(gon, 'http://lexvo.org/id/iso639-3/gon').
language(gor, 'http://lexvo.org/id/iso639-3/gor').
language(got, 'http://lexvo.org/id/iso639-3/got').
language(grb, 'http://lexvo.org/id/iso639-3/grb').
language(grc, 'http://lexvo.org/id/iso639-3/grc').
language(gre, 'http://lexvo.org/id/iso639-3/ell').
language(grn, 'http://lexvo.org/id/iso639-3/grn').
language(gsw, 'http://lexvo.org/id/iso639-3/gsw').
language(guj, 'http://lexvo.org/id/iso639-3/guj').
language(gwi, 'http://lexvo.org/id/iso639-3/gwi').
language(hai, 'http://lexvo.org/id/iso639-3/hai').
language(hat, 'http://lexvo.org/id/iso639-3/hat').
language(hau, 'http://lexvo.org/id/iso639-3/hau').
language(haw, 'http://lexvo.org/id/iso639-3/haw').
language(heb, 'http://lexvo.org/id/iso639-3/heb').
language(her, 'http://lexvo.org/id/iso639-3/her').
language(hil, 'http://lexvo.org/id/iso639-3/hil').
language(hin, 'http://lexvo.org/id/iso639-3/hin').
language(hit, 'http://lexvo.org/id/iso639-3/hit').
language(hmn, 'http://lexvo.org/id/iso639-3/hmn').
language(hmo, 'http://lexvo.org/id/iso639-3/hmo').
language(hrv, 'http://lexvo.org/id/iso639-3/hrv').
language(hsb, 'http://lexvo.org/id/iso639-3/hsb').
language(hun, 'http://lexvo.org/id/iso639-3/hun').
language(hup, 'http://lexvo.org/id/iso639-3/hup').
language(hye, 'http://lexvo.org/id/iso639-3/hye').
language(iba, 'http://lexvo.org/id/iso639-3/iba').
language(ibo, 'http://lexvo.org/id/iso639-3/ibo').
language(ice, 'http://lexvo.org/id/iso639-3/isl').
language(ido, 'http://lexvo.org/id/iso639-3/ido').
language(iii, 'http://lexvo.org/id/iso639-3/iii').
language(ijo, 'http://lexvo.org/id/iso639-5/ijo').
language(iku, 'http://lexvo.org/id/iso639-3/iku').
language(ile, 'http://lexvo.org/id/iso639-3/ile').
language(ilo, 'http://lexvo.org/id/iso639-3/ilo').
language(ina, 'http://lexvo.org/id/iso639-3/ina').
language(inc, 'http://lexvo.org/id/iso639-5/inc').
language(ind, 'http://lexvo.org/id/iso639-3/ind').
language(ine, 'http://lexvo.org/id/iso639-5/ine').
language(inh, 'http://lexvo.org/id/iso639-3/inh').
language(ipk, 'http://lexvo.org/id/iso639-3/ipk').
language(ira, 'http://lexvo.org/id/iso639-5/ira').
language(iro, 'http://lexvo.org/id/iso639-5/iro').
language(isl, 'http://lexvo.org/id/iso639-3/isl').
language(ita, 'http://lexvo.org/id/iso639-3/ita').
language(jav, 'http://lexvo.org/id/iso639-3/jav').
language(jbo, 'http://lexvo.org/id/iso639-3/jbo').
language(jpn, 'http://lexvo.org/id/iso639-3/jpn').
language(jpr, 'http://lexvo.org/id/iso639-3/jpr').
language(jrb, 'http://lexvo.org/id/iso639-3/jrb').
language(kaa, 'http://lexvo.org/id/iso639-3/kaa').
language(kab, 'http://lexvo.org/id/iso639-3/kab').
language(kac, 'http://lexvo.org/id/iso639-3/kac').
language(kal, 'http://lexvo.org/id/iso639-3/kal').
language(kam, 'http://lexvo.org/id/iso639-3/kam').
language(kan, 'http://lexvo.org/id/iso639-3/kan').
language(kar, 'http://lexvo.org/id/iso639-5/kar').
language(kas, 'http://lexvo.org/id/iso639-3/kas').
language(kat, 'http://lexvo.org/id/iso639-3/kat').
language(kau, 'http://lexvo.org/id/iso639-3/kau').
language(kaw, 'http://lexvo.org/id/iso639-3/kaw').
language(kaz, 'http://lexvo.org/id/iso639-3/kaz').
language(kbd, 'http://lexvo.org/id/iso639-3/kbd').
language(kha, 'http://lexvo.org/id/iso639-3/kha').
language(khi, 'http://lexvo.org/id/iso639-5/khi').
language(khm, 'http://lexvo.org/id/iso639-3/khm').
language(kho, 'http://lexvo.org/id/iso639-3/kho').
language(kik, 'http://lexvo.org/id/iso639-3/kik').
language(kin, 'http://lexvo.org/id/iso639-3/kin').
language(kir, 'http://lexvo.org/id/iso639-3/kir').
language(kmb, 'http://lexvo.org/id/iso639-3/kmb').
language(kok, 'http://lexvo.org/id/iso639-3/kok').
language(kom, 'http://lexvo.org/id/iso639-3/kom').
language(kon, 'http://lexvo.org/id/iso639-3/kon').
language(kor, 'http://lexvo.org/id/iso639-3/kor').
language(kos, 'http://lexvo.org/id/iso639-3/kos').
language(kpe, 'http://lexvo.org/id/iso639-3/kpe').
language(krc, 'http://lexvo.org/id/iso639-3/krc').
language(krl, 'http://lexvo.org/id/iso639-3/krl').
language(kro, 'http://lexvo.org/id/iso639-5/kro').
language(kru, 'http://lexvo.org/id/iso639-3/kru').
language(kua, 'http://lexvo.org/id/iso639-3/kua').
language(kum, 'http://lexvo.org/id/iso639-3/kum').
language(kur, 'http://lexvo.org/id/iso639-3/kur').
language(kut, 'http://lexvo.org/id/iso639-3/kut').
language(lad, 'http://lexvo.org/id/iso639-3/lad').
language(lah, 'http://lexvo.org/id/iso639-3/lah').
language(lam, 'http://lexvo.org/id/iso639-3/lam').
language(lao, 'http://lexvo.org/id/iso639-3/lao').
language(lat, 'http://lexvo.org/id/iso639-3/lat').
language(lav, 'http://lexvo.org/id/iso639-3/lav').
language(lez, 'http://lexvo.org/id/iso639-3/lez').
language(lim, 'http://lexvo.org/id/iso639-3/lim').
language(lin, 'http://lexvo.org/id/iso639-3/lin').
language(lit, 'http://lexvo.org/id/iso639-3/lit').
language(lol, 'http://lexvo.org/id/iso639-3/lol').
language(loz, 'http://lexvo.org/id/iso639-3/loz').
language(ltz, 'http://lexvo.org/id/iso639-3/ltz').
language(lua, 'http://lexvo.org/id/iso639-3/lua').
language(lub, 'http://lexvo.org/id/iso639-3/lub').
language(lug, 'http://lexvo.org/id/iso639-3/lug').
language(lui, 'http://lexvo.org/id/iso639-3/lui').
language(lun, 'http://lexvo.org/id/iso639-3/lun').
language(luo, 'http://lexvo.org/id/iso639-3/luo').
language(lus, 'http://lexvo.org/id/iso639-3/lus').
language(mac, 'http://lexvo.org/id/iso639-3/mkd').
language(mad, 'http://lexvo.org/id/iso639-3/mad').
language(mag, 'http://lexvo.org/id/iso639-3/mag').
language(mah, 'http://lexvo.org/id/iso639-3/mah').
language(mai, 'http://lexvo.org/id/iso639-3/mai').
language(mak, 'http://lexvo.org/id/iso639-3/mak').
language(mal, 'http://lexvo.org/id/iso639-3/mal').
language(man, 'http://lexvo.org/id/iso639-3/man').
language(mao, 'http://lexvo.org/id/iso639-3/mri').
language(map, 'http://lexvo.org/id/iso639-5/map').
language(mar, 'http://lexvo.org/id/iso639-3/mar').
language(mas, 'http://lexvo.org/id/iso639-3/mas').
language(may, 'http://lexvo.org/id/iso639-3/msa').
language(mdf, 'http://lexvo.org/id/iso639-3/mdf').
language(mdr, 'http://lexvo.org/id/iso639-3/mdr').
language(men, 'http://lexvo.org/id/iso639-3/men').
language(mga, 'http://lexvo.org/id/iso639-3/mga').
language(mic, 'http://lexvo.org/id/iso639-3/mic').
language(min, 'http://lexvo.org/id/iso639-3/min').
language(mis, 'http://lexvo.org/id/iso639-3/mis').
language(mkd, 'http://lexvo.org/id/iso639-3/mkd').
language(mkh, 'http://lexvo.org/id/iso639-5/mkh').
language(mlg, 'http://lexvo.org/id/iso639-3/mlg').
language(mlt, 'http://lexvo.org/id/iso639-3/mlt').
language(mnc, 'http://lexvo.org/id/iso639-3/mnc').
language(mni, 'http://lexvo.org/id/iso639-3/mni').
language(mno, 'http://lexvo.org/id/iso639-5/mno').
language(moh, 'http://lexvo.org/id/iso639-3/moh').
language(mon, 'http://lexvo.org/id/iso639-3/mon').
language(mos, 'http://lexvo.org/id/iso639-3/mos').
language(mri, 'http://lexvo.org/id/iso639-3/mri').
language(msa, 'http://lexvo.org/id/iso639-3/msa').
language(mul, 'http://lexvo.org/id/iso639-3/mul').
language(mun, 'http://lexvo.org/id/iso639-5/mun').
language(mus, 'http://lexvo.org/id/iso639-3/mus').
language(mwl, 'http://lexvo.org/id/iso639-3/mwl').
language(mwr, 'http://lexvo.org/id/iso639-3/mwr').
language(mya, 'http://lexvo.org/id/iso639-3/mya').
language(myn, 'http://lexvo.org/id/iso639-5/myn').
language(myv, 'http://lexvo.org/id/iso639-3/myv').
language(nah, 'http://lexvo.org/id/iso639-5/nah').
language(nai, 'http://lexvo.org/id/iso639-5/nai').
language(nap, 'http://lexvo.org/id/iso639-3/nap').
language(nau, 'http://lexvo.org/id/iso639-3/nau').
language(nav, 'http://lexvo.org/id/iso639-3/nav').
language(nbl, 'http://lexvo.org/id/iso639-3/nbl').
language(nde, 'http://lexvo.org/id/iso639-3/nde').
language(ndo, 'http://lexvo.org/id/iso639-3/ndo').
language(nds, 'http://lexvo.org/id/iso639-3/nds').
language(nep, 'http://lexvo.org/id/iso639-3/nep').
language(new, 'http://lexvo.org/id/iso639-3/new').
language(nia, 'http://lexvo.org/id/iso639-3/nia').
language(nic, 'http://lexvo.org/id/iso639-5/nic').
language(niu, 'http://lexvo.org/id/iso639-3/niu').
language(nld, 'http://lexvo.org/id/iso639-3/nld').
language(nno, 'http://lexvo.org/id/iso639-3/nno').
language(nob, 'http://lexvo.org/id/iso639-3/nob').
language(nog, 'http://lexvo.org/id/iso639-3/nog').
language(non, 'http://lexvo.org/id/iso639-3/non').
language(nor, 'http://lexvo.org/id/iso639-3/nor').
language(nqo, 'http://lexvo.org/id/iso639-3/nqo').
language(nso, 'http://lexvo.org/id/iso639-3/nso').
language(nub, 'http://lexvo.org/id/iso639-5/nub').
language(nwc, 'http://lexvo.org/id/iso639-3/nwc').
language(nya, 'http://lexvo.org/id/iso639-3/nya').
language(nym, 'http://lexvo.org/id/iso639-3/nym').
language(nyn, 'http://lexvo.org/id/iso639-3/nyn').
language(nyo, 'http://lexvo.org/id/iso639-3/nyo').
language(nzi, 'http://lexvo.org/id/iso639-3/nzi').
language(oci, 'http://lexvo.org/id/iso639-3/oci').
language(oji, 'http://lexvo.org/id/iso639-3/oji').
language(ori, 'http://lexvo.org/id/iso639-3/ori').
language(orm, 'http://lexvo.org/id/iso639-3/orm').
language(osa, 'http://lexvo.org/id/iso639-3/osa').
language(oss, 'http://lexvo.org/id/iso639-3/oss').
language(ota, 'http://lexvo.org/id/iso639-3/ota').
language(oto, 'http://lexvo.org/id/iso639-5/oto').
language(paa, 'http://lexvo.org/id/iso639-5/paa').
language(pag, 'http://lexvo.org/id/iso639-3/pag').
language(pal, 'http://lexvo.org/id/iso639-3/pal').
language(pam, 'http://lexvo.org/id/iso639-3/pam').
language(pan, 'http://lexvo.org/id/iso639-3/pan').
language(pap, 'http://lexvo.org/id/iso639-3/pap').
language(pau, 'http://lexvo.org/id/iso639-3/pau').
language(peo, 'http://lexvo.org/id/iso639-3/peo').
language(per, 'http://lexvo.org/id/iso639-3/fas').
language(phi, 'http://lexvo.org/id/iso639-5/phi').
language(phn, 'http://lexvo.org/id/iso639-3/phn').
language(pli, 'http://lexvo.org/id/iso639-3/pli').
language(pol, 'http://lexvo.org/id/iso639-3/pol').
language(pon, 'http://lexvo.org/id/iso639-3/pon').
language(por, 'http://lexvo.org/id/iso639-3/por').
language(pra, 'http://lexvo.org/id/iso639-5/pra').
language(pro, 'http://lexvo.org/id/iso639-3/pro').
language(pus, 'http://lexvo.org/id/iso639-3/pus').
language(que, 'http://lexvo.org/id/iso639-3/que').
language(raj, 'http://lexvo.org/id/iso639-3/raj').
language(rap, 'http://lexvo.org/id/iso639-3/rap').
language(rar, 'http://lexvo.org/id/iso639-3/rar').
language(roa, 'http://lexvo.org/id/iso639-5/roa').
language(roh, 'http://lexvo.org/id/iso639-3/roh').
language(rom, 'http://lexvo.org/id/iso639-3/rom').
language(ron, 'http://lexvo.org/id/iso639-3/ron').
language(rum, 'http://lexvo.org/id/iso639-3/ron').
language(run, 'http://lexvo.org/id/iso639-3/run').
language(rup, 'http://lexvo.org/id/iso639-3/rup').
language(rus, 'http://lexvo.org/id/iso639-3/rus').
language(sad, 'http://lexvo.org/id/iso639-3/sad').
language(sag, 'http://lexvo.org/id/iso639-3/sag').
language(sah, 'http://lexvo.org/id/iso639-3/sah').
language(sai, 'http://lexvo.org/id/iso639-5/sai').
language(sal, 'http://lexvo.org/id/iso639-5/sal').
language(sam, 'http://lexvo.org/id/iso639-3/sam').
language(san, 'http://lexvo.org/id/iso639-3/san').
language(sas, 'http://lexvo.org/id/iso639-3/sas').
language(sat, 'http://lexvo.org/id/iso639-3/sat').
language(scn, 'http://lexvo.org/id/iso639-3/scn').
language(sco, 'http://lexvo.org/id/iso639-3/sco').
language(sel, 'http://lexvo.org/id/iso639-3/sel').
language(sem, 'http://lexvo.org/id/iso639-5/sem').
language(sga, 'http://lexvo.org/id/iso639-3/sga').
language(sgn, 'http://lexvo.org/id/iso639-5/sgn').
language(shn, 'http://lexvo.org/id/iso639-3/shn').
language(sid, 'http://lexvo.org/id/iso639-3/sid').
language(sin, 'http://lexvo.org/id/iso639-3/sin').
language(sio, 'http://lexvo.org/id/iso639-5/sio').
language(sit, 'http://lexvo.org/id/iso639-5/sit').
language(sla, 'http://lexvo.org/id/iso639-5/sla').
language(slk, 'http://lexvo.org/id/iso639-3/slk').
language(slo, 'http://lexvo.org/id/iso639-3/slk').
language(slv, 'http://lexvo.org/id/iso639-3/slv').
language(sma, 'http://lexvo.org/id/iso639-3/sma').
language(sme, 'http://lexvo.org/id/iso639-3/sme').
language(smi, 'http://lexvo.org/id/iso639-5/smi').
language(smj, 'http://lexvo.org/id/iso639-3/smj').
language(smn, 'http://lexvo.org/id/iso639-3/smn').
language(smo, 'http://lexvo.org/id/iso639-3/smo').
language(sms, 'http://lexvo.org/id/iso639-3/sms').
language(sna, 'http://lexvo.org/id/iso639-3/sna').
language(snd, 'http://lexvo.org/id/iso639-3/snd').
language(snk, 'http://lexvo.org/id/iso639-3/snk').
language(sog, 'http://lexvo.org/id/iso639-3/sog').
language(som, 'http://lexvo.org/id/iso639-3/som').
language(son, 'http://lexvo.org/id/iso639-5/son').
language(sot, 'http://lexvo.org/id/iso639-3/sot').
language(spa, 'http://lexvo.org/id/iso639-3/spa').
language(sqi, 'http://lexvo.org/id/iso639-3/sqi').
language(srd, 'http://lexvo.org/id/iso639-3/srd').
language(srn, 'http://lexvo.org/id/iso639-3/srn').
language(srp, 'http://lexvo.org/id/iso639-3/srp').
language(srr, 'http://lexvo.org/id/iso639-3/srr').
language(ssa, 'http://lexvo.org/id/iso639-5/ssa').
language(ssw, 'http://lexvo.org/id/iso639-3/ssw').
language(suk, 'http://lexvo.org/id/iso639-3/suk').
language(sun, 'http://lexvo.org/id/iso639-3/sun').
language(sus, 'http://lexvo.org/id/iso639-3/sus').
language(sux, 'http://lexvo.org/id/iso639-3/sux').
language(swa, 'http://lexvo.org/id/iso639-3/swa').
language(swe, 'http://lexvo.org/id/iso639-3/swe').
language(syc, 'http://lexvo.org/id/iso639-3/syc').
language(syr, 'http://lexvo.org/id/iso639-3/syr').
language(tah, 'http://lexvo.org/id/iso639-3/tah').
language(tai, 'http://lexvo.org/id/iso639-5/tai').
language(tam, 'http://lexvo.org/id/iso639-3/tam').
language(tat, 'http://lexvo.org/id/iso639-3/tat').
language(tel, 'http://lexvo.org/id/iso639-3/tel').
language(tem, 'http://lexvo.org/id/iso639-3/tem').
language(ter, 'http://lexvo.org/id/iso639-3/ter').
language(tet, 'http://lexvo.org/id/iso639-3/tet').
language(tgk, 'http://lexvo.org/id/iso639-3/tgk').
language(tgl, 'http://lexvo.org/id/iso639-3/tgl').
language(tha, 'http://lexvo.org/id/iso639-3/tha').
language(tib, 'http://lexvo.org/id/iso639-3/bod').
language(tig, 'http://lexvo.org/id/iso639-3/tig').
language(tir, 'http://lexvo.org/id/iso639-3/tir').
language(tiv, 'http://lexvo.org/id/iso639-3/tiv').
language(tkl, 'http://lexvo.org/id/iso639-3/tkl').
language(tlh, 'http://lexvo.org/id/iso639-3/tlh').
language(tli, 'http://lexvo.org/id/iso639-3/tli').
language(tmh, 'http://lexvo.org/id/iso639-3/tmh').
language(tog, 'http://lexvo.org/id/iso639-3/tog').
language(ton, 'http://lexvo.org/id/iso639-3/ton').
language(tpi, 'http://lexvo.org/id/iso639-3/tpi').
language(tsi, 'http://lexvo.org/id/iso639-3/tsi').
language(tsn, 'http://lexvo.org/id/iso639-3/tsn').
language(tso, 'http://lexvo.org/id/iso639-3/tso').
language(tuk, 'http://lexvo.org/id/iso639-3/tuk').
language(tum, 'http://lexvo.org/id/iso639-3/tum').
language(tup, 'http://lexvo.org/id/iso639-5/tup').
language(tur, 'http://lexvo.org/id/iso639-3/tur').
language(tut, 'http://lexvo.org/id/iso639-5/tut').
language(tvl, 'http://lexvo.org/id/iso639-3/tvl').
language(twi, 'http://lexvo.org/id/iso639-3/twi').
language(tyv, 'http://lexvo.org/id/iso639-3/tyv').
language(udm, 'http://lexvo.org/id/iso639-3/udm').
language(uga, 'http://lexvo.org/id/iso639-3/uga').
language(uig, 'http://lexvo.org/id/iso639-3/uig').
language(ukr, 'http://lexvo.org/id/iso639-3/ukr').
language(umb, 'http://lexvo.org/id/iso639-3/umb').
language(und, 'http://lexvo.org/id/iso639-3/und').
language(urd, 'http://lexvo.org/id/iso639-3/urd').
language(uzb, 'http://lexvo.org/id/iso639-3/uzb').
language(vai, 'http://lexvo.org/id/iso639-3/vai').
language(ven, 'http://lexvo.org/id/iso639-3/ven').
language(vie, 'http://lexvo.org/id/iso639-3/vie').
language(vol, 'http://lexvo.org/id/iso639-3/vol').
language(vot, 'http://lexvo.org/id/iso639-3/vot').
language(wak, 'http://lexvo.org/id/iso639-5/wak').
language(wal, 'http://lexvo.org/id/iso639-3/wal').
language(war, 'http://lexvo.org/id/iso639-3/war').
language(was, 'http://lexvo.org/id/iso639-3/was').
language(wel, 'http://lexvo.org/id/iso639-3/cym').
language(wen, 'http://lexvo.org/id/iso639-5/wen').
language(wln, 'http://lexvo.org/id/iso639-3/wln').
language(wol, 'http://lexvo.org/id/iso639-3/wol').
language(xal, 'http://lexvo.org/id/iso639-3/xal').
language(xho, 'http://lexvo.org/id/iso639-3/xho').
language(yao, 'http://lexvo.org/id/iso639-3/yao').
language(yap, 'http://lexvo.org/id/iso639-3/yap').
language(yid, 'http://lexvo.org/id/iso639-3/yid').
language(yor, 'http://lexvo.org/id/iso639-3/yor').
language(ypk, 'http://lexvo.org/id/iso639-5/ypk').
language(zap, 'http://lexvo.org/id/iso639-3/zap').
language(zbl, 'http://lexvo.org/id/iso639-3/zbl').
language(zen, 'http://lexvo.org/id/iso639-3/zen').
language(zha, 'http://lexvo.org/id/iso639-3/zha').
language(zho, 'http://lexvo.org/id/iso639-3/zho').
language(znd, 'http://lexvo.org/id/iso639-5/znd').
language(zul, 'http://lexvo.org/id/iso639-3/zul').
language(zun, 'http://lexvo.org/id/iso639-3/zun').
language(zza, 'http://lexvo.org/id/iso639-3/zza').

