:- module(
  iso_639_2,
  [
    iso_639_2_language/2 % ?ISO:atom
                         % ?Lexvo:uri
  ]
).

/** <module> ISO 639-2

The ISO 639-2 standard for language codes with Lexvo Semantic Web URIs.

!!iso_639_2!!language0!!2!!

WWW: [http://www.sil.org/iso639-2/]

@author Wouter Beek
@version 2013/01
*/


iso_639_2_language(ISO, Lexvo):-
  language0(ISO, Lexvo).

%% language0(?ISO:atom, ?Lexvo:uri) is nondet.

language0(aar, 'http://lexvo.org/id/iso639-3/aar').
language0(abk, 'http://lexvo.org/id/iso639-3/abk').
language0(ace, 'http://lexvo.org/id/iso639-3/ace').
language0(ach, 'http://lexvo.org/id/iso639-3/ach').
language0(ada, 'http://lexvo.org/id/iso639-3/ada').
language0(ady, 'http://lexvo.org/id/iso639-3/ady').
language0(afa, 'http://lexvo.org/id/iso639-5/afa').
language0(afh, 'http://lexvo.org/id/iso639-3/afh').
language0(afr, 'http://lexvo.org/id/iso639-3/afr').
language0(ain, 'http://lexvo.org/id/iso639-3/ain').
language0(aka, 'http://lexvo.org/id/iso639-3/aka').
language0(akk, 'http://lexvo.org/id/iso639-3/akk').
language0(alb, 'http://lexvo.org/id/iso639-3/sqi').
language0(ale, 'http://lexvo.org/id/iso639-3/ale').
language0(alg, 'http://lexvo.org/id/iso639-5/alg').
language0(alt, 'http://lexvo.org/id/iso639-3/alt').
language0(amh, 'http://lexvo.org/id/iso639-3/amh').
language0(ang, 'http://lexvo.org/id/iso639-3/ang').
language0(anp, 'http://lexvo.org/id/iso639-3/anp').
language0(apa, 'http://lexvo.org/id/iso639-5/apa').
language0(ara, 'http://lexvo.org/id/iso639-3/ara').
language0(arc, 'http://lexvo.org/id/iso639-3/arc').
language0(arg, 'http://lexvo.org/id/iso639-3/arg').
language0(arm, 'http://lexvo.org/id/iso639-3/hye').
language0(arn, 'http://lexvo.org/id/iso639-3/arn').
language0(arp, 'http://lexvo.org/id/iso639-3/arp').
language0(art, 'http://lexvo.org/id/iso639-5/art').
language0(arw, 'http://lexvo.org/id/iso639-3/arw').
language0(asm, 'http://lexvo.org/id/iso639-3/asm').
language0(ast, 'http://lexvo.org/id/iso639-3/ast').
language0(ath, 'http://lexvo.org/id/iso639-5/ath').
language0(aus, 'http://lexvo.org/id/iso639-5/aus').
language0(ava, 'http://lexvo.org/id/iso639-3/ava').
language0(ave, 'http://lexvo.org/id/iso639-3/ave').
language0(awa, 'http://lexvo.org/id/iso639-3/awa').
language0(aym, 'http://lexvo.org/id/iso639-3/aym').
language0(aze, 'http://lexvo.org/id/iso639-3/aze').
language0(bad, 'http://lexvo.org/id/iso639-5/bad').
language0(bai, 'http://lexvo.org/id/iso639-5/bai').
language0(bak, 'http://lexvo.org/id/iso639-3/bak').
language0(bal, 'http://lexvo.org/id/iso639-3/bal').
language0(bam, 'http://lexvo.org/id/iso639-3/bam').
language0(ban, 'http://lexvo.org/id/iso639-3/ban').
language0(baq, 'http://lexvo.org/id/iso639-3/eus').
language0(bas, 'http://lexvo.org/id/iso639-3/bas').
language0(bat, 'http://lexvo.org/id/iso639-5/bat').
language0(bej, 'http://lexvo.org/id/iso639-3/bej').
language0(bel, 'http://lexvo.org/id/iso639-3/bel').
language0(bem, 'http://lexvo.org/id/iso639-3/bem').
language0(ben, 'http://lexvo.org/id/iso639-3/ben').
language0(ber, 'http://lexvo.org/id/iso639-5/ber').
language0(bho, 'http://lexvo.org/id/iso639-3/bho').
language0(bik, 'http://lexvo.org/id/iso639-3/bik').
language0(bin, 'http://lexvo.org/id/iso639-3/bin').
language0(bis, 'http://lexvo.org/id/iso639-3/bis').
language0(bla, 'http://lexvo.org/id/iso639-3/bla').
language0(bnt, 'http://lexvo.org/id/iso639-5/bnt').
language0(bod, 'http://lexvo.org/id/iso639-3/bod').
language0(bos, 'http://lexvo.org/id/iso639-3/bos').
language0(bra, 'http://lexvo.org/id/iso639-3/bra').
language0(bre, 'http://lexvo.org/id/iso639-3/bre').
language0(btk, 'http://lexvo.org/id/iso639-5/btk').
language0(bua, 'http://lexvo.org/id/iso639-3/bua').
language0(bug, 'http://lexvo.org/id/iso639-3/bug').
language0(bul, 'http://lexvo.org/id/iso639-3/bul').
language0(bur, 'http://lexvo.org/id/iso639-3/mya').
language0(byn, 'http://lexvo.org/id/iso639-3/byn').
language0(cad, 'http://lexvo.org/id/iso639-3/cad').
language0(cai, 'http://lexvo.org/id/iso639-5/cai').
language0(car, 'http://lexvo.org/id/iso639-3/car').
language0(cat, 'http://lexvo.org/id/iso639-3/cat').
language0(cau, 'http://lexvo.org/id/iso639-5/cau').
language0(ceb, 'http://lexvo.org/id/iso639-3/ceb').
language0(cel, 'http://lexvo.org/id/iso639-5/cel').
language0(ces, 'http://lexvo.org/id/iso639-3/ces').
language0(cha, 'http://lexvo.org/id/iso639-3/cha').
language0(chb, 'http://lexvo.org/id/iso639-3/chb').
language0(che, 'http://lexvo.org/id/iso639-3/che').
language0(chg, 'http://lexvo.org/id/iso639-3/chg').
language0(chi, 'http://lexvo.org/id/iso639-3/zho').
language0(chk, 'http://lexvo.org/id/iso639-3/chk').
language0(chm, 'http://lexvo.org/id/iso639-3/chm').
language0(chn, 'http://lexvo.org/id/iso639-3/chn').
language0(cho, 'http://lexvo.org/id/iso639-3/cho').
language0(chp, 'http://lexvo.org/id/iso639-3/chp').
language0(chr, 'http://lexvo.org/id/iso639-3/chr').
language0(chu, 'http://lexvo.org/id/iso639-3/chu').
language0(chv, 'http://lexvo.org/id/iso639-3/chv').
language0(chy, 'http://lexvo.org/id/iso639-3/chy').
language0(cmc, 'http://lexvo.org/id/iso639-5/cmc').
language0(cop, 'http://lexvo.org/id/iso639-3/cop').
language0(cor, 'http://lexvo.org/id/iso639-3/cor').
language0(cos, 'http://lexvo.org/id/iso639-3/cos').
language0(cpe, 'http://lexvo.org/id/iso639-5/cpe').
language0(cpf, 'http://lexvo.org/id/iso639-5/cpf').
language0(cpp, 'http://lexvo.org/id/iso639-5/cpp').
language0(cre, 'http://lexvo.org/id/iso639-3/cre').
language0(crh, 'http://lexvo.org/id/iso639-3/crh').
language0(crp, 'http://lexvo.org/id/iso639-5/crp').
language0(csb, 'http://lexvo.org/id/iso639-3/csb').
language0(cus, 'http://lexvo.org/id/iso639-5/cus').
language0(cym, 'http://lexvo.org/id/iso639-3/cym').
language0(cze, 'http://lexvo.org/id/iso639-3/ces').
language0(dak, 'http://lexvo.org/id/iso639-3/dak').
language0(dan, 'http://lexvo.org/id/iso639-3/dan').
language0(dar, 'http://lexvo.org/id/iso639-3/dar').
language0(day, 'http://lexvo.org/id/iso639-5/day').
language0(del, 'http://lexvo.org/id/iso639-3/del').
language0(den, 'http://lexvo.org/id/iso639-3/den').
language0(deu, 'http://lexvo.org/id/iso639-3/deu').
language0(dgr, 'http://lexvo.org/id/iso639-3/dgr').
language0(din, 'http://lexvo.org/id/iso639-3/din').
language0(div, 'http://lexvo.org/id/iso639-3/div').
language0(doi, 'http://lexvo.org/id/iso639-3/doi').
language0(dra, 'http://lexvo.org/id/iso639-5/dra').
language0(dsb, 'http://lexvo.org/id/iso639-3/dsb').
language0(dua, 'http://lexvo.org/id/iso639-3/dua').
language0(dum, 'http://lexvo.org/id/iso639-3/dum').
language0(dut, 'http://lexvo.org/id/iso639-3/nld').
language0(dyu, 'http://lexvo.org/id/iso639-3/dyu').
language0(dzo, 'http://lexvo.org/id/iso639-3/dzo').
language0(efi, 'http://lexvo.org/id/iso639-3/efi').
language0(egy, 'http://lexvo.org/id/iso639-3/egy').
language0(eka, 'http://lexvo.org/id/iso639-3/eka').
language0(ell, 'http://lexvo.org/id/iso639-3/ell').
language0(elx, 'http://lexvo.org/id/iso639-3/elx').
language0(eng, 'http://lexvo.org/id/iso639-3/eng').
language0(enm, 'http://lexvo.org/id/iso639-3/enm').
language0(epo, 'http://lexvo.org/id/iso639-3/epo').
language0(est, 'http://lexvo.org/id/iso639-3/est').
language0(eus, 'http://lexvo.org/id/iso639-3/eus').
language0(ewe, 'http://lexvo.org/id/iso639-3/ewe').
language0(ewo, 'http://lexvo.org/id/iso639-3/ewo').
language0(fan, 'http://lexvo.org/id/iso639-3/fan').
language0(fao, 'http://lexvo.org/id/iso639-3/fao').
language0(fas, 'http://lexvo.org/id/iso639-3/fas').
language0(fat, 'http://lexvo.org/id/iso639-3/fat').
language0(fij, 'http://lexvo.org/id/iso639-3/fij').
language0(fil, 'http://lexvo.org/id/iso639-3/fil').
language0(fin, 'http://lexvo.org/id/iso639-3/fin').
language0(fiu, 'http://lexvo.org/id/iso639-5/fiu').
language0(fon, 'http://lexvo.org/id/iso639-3/fon').
language0(fra, 'http://lexvo.org/id/iso639-3/fra').
language0(fre, 'http://lexvo.org/id/iso639-3/fra').
language0(frm, 'http://lexvo.org/id/iso639-3/frm').
language0(fro, 'http://lexvo.org/id/iso639-3/fro').
language0(frr, 'http://lexvo.org/id/iso639-3/frr').
language0(frs, 'http://lexvo.org/id/iso639-3/frs').
language0(fry, 'http://lexvo.org/id/iso639-3/fry').
language0(ful, 'http://lexvo.org/id/iso639-3/ful').
language0(fur, 'http://lexvo.org/id/iso639-3/fur').
language0(gaa, 'http://lexvo.org/id/iso639-3/gaa').
language0(gay, 'http://lexvo.org/id/iso639-3/gay').
language0(gba, 'http://lexvo.org/id/iso639-3/gba').
language0(gem, 'http://lexvo.org/id/iso639-5/gem').
language0(geo, 'http://lexvo.org/id/iso639-3/kat').
language0(ger, 'http://lexvo.org/id/iso639-3/deu').
language0(gez, 'http://lexvo.org/id/iso639-3/gez').
language0(gil, 'http://lexvo.org/id/iso639-3/gil').
language0(gla, 'http://lexvo.org/id/iso639-3/gla').
language0(gle, 'http://lexvo.org/id/iso639-3/gle').
language0(glg, 'http://lexvo.org/id/iso639-3/glg').
language0(glv, 'http://lexvo.org/id/iso639-3/glv').
language0(gmh, 'http://lexvo.org/id/iso639-3/gmh').
language0(goh, 'http://lexvo.org/id/iso639-3/goh').
language0(gon, 'http://lexvo.org/id/iso639-3/gon').
language0(gor, 'http://lexvo.org/id/iso639-3/gor').
language0(got, 'http://lexvo.org/id/iso639-3/got').
language0(grb, 'http://lexvo.org/id/iso639-3/grb').
language0(grc, 'http://lexvo.org/id/iso639-3/grc').
language0(gre, 'http://lexvo.org/id/iso639-3/ell').
language0(grn, 'http://lexvo.org/id/iso639-3/grn').
language0(gsw, 'http://lexvo.org/id/iso639-3/gsw').
language0(guj, 'http://lexvo.org/id/iso639-3/guj').
language0(gwi, 'http://lexvo.org/id/iso639-3/gwi').
language0(hai, 'http://lexvo.org/id/iso639-3/hai').
language0(hat, 'http://lexvo.org/id/iso639-3/hat').
language0(hau, 'http://lexvo.org/id/iso639-3/hau').
language0(haw, 'http://lexvo.org/id/iso639-3/haw').
language0(heb, 'http://lexvo.org/id/iso639-3/heb').
language0(her, 'http://lexvo.org/id/iso639-3/her').
language0(hil, 'http://lexvo.org/id/iso639-3/hil').
language0(hin, 'http://lexvo.org/id/iso639-3/hin').
language0(hit, 'http://lexvo.org/id/iso639-3/hit').
language0(hmn, 'http://lexvo.org/id/iso639-3/hmn').
language0(hmo, 'http://lexvo.org/id/iso639-3/hmo').
language0(hrv, 'http://lexvo.org/id/iso639-3/hrv').
language0(hsb, 'http://lexvo.org/id/iso639-3/hsb').
language0(hun, 'http://lexvo.org/id/iso639-3/hun').
language0(hup, 'http://lexvo.org/id/iso639-3/hup').
language0(hye, 'http://lexvo.org/id/iso639-3/hye').
language0(iba, 'http://lexvo.org/id/iso639-3/iba').
language0(ibo, 'http://lexvo.org/id/iso639-3/ibo').
language0(ice, 'http://lexvo.org/id/iso639-3/isl').
language0(ido, 'http://lexvo.org/id/iso639-3/ido').
language0(iii, 'http://lexvo.org/id/iso639-3/iii').
language0(ijo, 'http://lexvo.org/id/iso639-5/ijo').
language0(iku, 'http://lexvo.org/id/iso639-3/iku').
language0(ile, 'http://lexvo.org/id/iso639-3/ile').
language0(ilo, 'http://lexvo.org/id/iso639-3/ilo').
language0(ina, 'http://lexvo.org/id/iso639-3/ina').
language0(inc, 'http://lexvo.org/id/iso639-5/inc').
language0(ind, 'http://lexvo.org/id/iso639-3/ind').
language0(ine, 'http://lexvo.org/id/iso639-5/ine').
language0(inh, 'http://lexvo.org/id/iso639-3/inh').
language0(ipk, 'http://lexvo.org/id/iso639-3/ipk').
language0(ira, 'http://lexvo.org/id/iso639-5/ira').
language0(iro, 'http://lexvo.org/id/iso639-5/iro').
language0(isl, 'http://lexvo.org/id/iso639-3/isl').
language0(ita, 'http://lexvo.org/id/iso639-3/ita').
language0(jav, 'http://lexvo.org/id/iso639-3/jav').
language0(jbo, 'http://lexvo.org/id/iso639-3/jbo').
language0(jpn, 'http://lexvo.org/id/iso639-3/jpn').
language0(jpr, 'http://lexvo.org/id/iso639-3/jpr').
language0(jrb, 'http://lexvo.org/id/iso639-3/jrb').
language0(kaa, 'http://lexvo.org/id/iso639-3/kaa').
language0(kab, 'http://lexvo.org/id/iso639-3/kab').
language0(kac, 'http://lexvo.org/id/iso639-3/kac').
language0(kal, 'http://lexvo.org/id/iso639-3/kal').
language0(kam, 'http://lexvo.org/id/iso639-3/kam').
language0(kan, 'http://lexvo.org/id/iso639-3/kan').
language0(kar, 'http://lexvo.org/id/iso639-5/kar').
language0(kas, 'http://lexvo.org/id/iso639-3/kas').
language0(kat, 'http://lexvo.org/id/iso639-3/kat').
language0(kau, 'http://lexvo.org/id/iso639-3/kau').
language0(kaw, 'http://lexvo.org/id/iso639-3/kaw').
language0(kaz, 'http://lexvo.org/id/iso639-3/kaz').
language0(kbd, 'http://lexvo.org/id/iso639-3/kbd').
language0(kha, 'http://lexvo.org/id/iso639-3/kha').
language0(khi, 'http://lexvo.org/id/iso639-5/khi').
language0(khm, 'http://lexvo.org/id/iso639-3/khm').
language0(kho, 'http://lexvo.org/id/iso639-3/kho').
language0(kik, 'http://lexvo.org/id/iso639-3/kik').
language0(kin, 'http://lexvo.org/id/iso639-3/kin').
language0(kir, 'http://lexvo.org/id/iso639-3/kir').
language0(kmb, 'http://lexvo.org/id/iso639-3/kmb').
language0(kok, 'http://lexvo.org/id/iso639-3/kok').
language0(kom, 'http://lexvo.org/id/iso639-3/kom').
language0(kon, 'http://lexvo.org/id/iso639-3/kon').
language0(kor, 'http://lexvo.org/id/iso639-3/kor').
language0(kos, 'http://lexvo.org/id/iso639-3/kos').
language0(kpe, 'http://lexvo.org/id/iso639-3/kpe').
language0(krc, 'http://lexvo.org/id/iso639-3/krc').
language0(krl, 'http://lexvo.org/id/iso639-3/krl').
language0(kro, 'http://lexvo.org/id/iso639-5/kro').
language0(kru, 'http://lexvo.org/id/iso639-3/kru').
language0(kua, 'http://lexvo.org/id/iso639-3/kua').
language0(kum, 'http://lexvo.org/id/iso639-3/kum').
language0(kur, 'http://lexvo.org/id/iso639-3/kur').
language0(kut, 'http://lexvo.org/id/iso639-3/kut').
language0(lad, 'http://lexvo.org/id/iso639-3/lad').
language0(lah, 'http://lexvo.org/id/iso639-3/lah').
language0(lam, 'http://lexvo.org/id/iso639-3/lam').
language0(lao, 'http://lexvo.org/id/iso639-3/lao').
language0(lat, 'http://lexvo.org/id/iso639-3/lat').
language0(lav, 'http://lexvo.org/id/iso639-3/lav').
language0(lez, 'http://lexvo.org/id/iso639-3/lez').
language0(lim, 'http://lexvo.org/id/iso639-3/lim').
language0(lin, 'http://lexvo.org/id/iso639-3/lin').
language0(lit, 'http://lexvo.org/id/iso639-3/lit').
language0(lol, 'http://lexvo.org/id/iso639-3/lol').
language0(loz, 'http://lexvo.org/id/iso639-3/loz').
language0(ltz, 'http://lexvo.org/id/iso639-3/ltz').
language0(lua, 'http://lexvo.org/id/iso639-3/lua').
language0(lub, 'http://lexvo.org/id/iso639-3/lub').
language0(lug, 'http://lexvo.org/id/iso639-3/lug').
language0(lui, 'http://lexvo.org/id/iso639-3/lui').
language0(lun, 'http://lexvo.org/id/iso639-3/lun').
language0(luo, 'http://lexvo.org/id/iso639-3/luo').
language0(lus, 'http://lexvo.org/id/iso639-3/lus').
language0(mac, 'http://lexvo.org/id/iso639-3/mkd').
language0(mad, 'http://lexvo.org/id/iso639-3/mad').
language0(mag, 'http://lexvo.org/id/iso639-3/mag').
language0(mah, 'http://lexvo.org/id/iso639-3/mah').
language0(mai, 'http://lexvo.org/id/iso639-3/mai').
language0(mak, 'http://lexvo.org/id/iso639-3/mak').
language0(mal, 'http://lexvo.org/id/iso639-3/mal').
language0(man, 'http://lexvo.org/id/iso639-3/man').
language0(mao, 'http://lexvo.org/id/iso639-3/mri').
language0(map, 'http://lexvo.org/id/iso639-5/map').
language0(mar, 'http://lexvo.org/id/iso639-3/mar').
language0(mas, 'http://lexvo.org/id/iso639-3/mas').
language0(may, 'http://lexvo.org/id/iso639-3/msa').
language0(mdf, 'http://lexvo.org/id/iso639-3/mdf').
language0(mdr, 'http://lexvo.org/id/iso639-3/mdr').
language0(men, 'http://lexvo.org/id/iso639-3/men').
language0(mga, 'http://lexvo.org/id/iso639-3/mga').
language0(mic, 'http://lexvo.org/id/iso639-3/mic').
language0(min, 'http://lexvo.org/id/iso639-3/min').
language0(mis, 'http://lexvo.org/id/iso639-3/mis').
language0(mkd, 'http://lexvo.org/id/iso639-3/mkd').
language0(mkh, 'http://lexvo.org/id/iso639-5/mkh').
language0(mlg, 'http://lexvo.org/id/iso639-3/mlg').
language0(mlt, 'http://lexvo.org/id/iso639-3/mlt').
language0(mnc, 'http://lexvo.org/id/iso639-3/mnc').
language0(mni, 'http://lexvo.org/id/iso639-3/mni').
language0(mno, 'http://lexvo.org/id/iso639-5/mno').
language0(moh, 'http://lexvo.org/id/iso639-3/moh').
language0(mon, 'http://lexvo.org/id/iso639-3/mon').
language0(mos, 'http://lexvo.org/id/iso639-3/mos').
language0(mri, 'http://lexvo.org/id/iso639-3/mri').
language0(msa, 'http://lexvo.org/id/iso639-3/msa').
language0(mul, 'http://lexvo.org/id/iso639-3/mul').
language0(mun, 'http://lexvo.org/id/iso639-5/mun').
language0(mus, 'http://lexvo.org/id/iso639-3/mus').
language0(mwl, 'http://lexvo.org/id/iso639-3/mwl').
language0(mwr, 'http://lexvo.org/id/iso639-3/mwr').
language0(mya, 'http://lexvo.org/id/iso639-3/mya').
language0(myn, 'http://lexvo.org/id/iso639-5/myn').
language0(myv, 'http://lexvo.org/id/iso639-3/myv').
language0(nah, 'http://lexvo.org/id/iso639-5/nah').
language0(nai, 'http://lexvo.org/id/iso639-5/nai').
language0(nap, 'http://lexvo.org/id/iso639-3/nap').
language0(nau, 'http://lexvo.org/id/iso639-3/nau').
language0(nav, 'http://lexvo.org/id/iso639-3/nav').
language0(nbl, 'http://lexvo.org/id/iso639-3/nbl').
language0(nde, 'http://lexvo.org/id/iso639-3/nde').
language0(ndo, 'http://lexvo.org/id/iso639-3/ndo').
language0(nds, 'http://lexvo.org/id/iso639-3/nds').
language0(nep, 'http://lexvo.org/id/iso639-3/nep').
language0(new, 'http://lexvo.org/id/iso639-3/new').
language0(nia, 'http://lexvo.org/id/iso639-3/nia').
language0(nic, 'http://lexvo.org/id/iso639-5/nic').
language0(niu, 'http://lexvo.org/id/iso639-3/niu').
language0(nld, 'http://lexvo.org/id/iso639-3/nld').
language0(nno, 'http://lexvo.org/id/iso639-3/nno').
language0(nob, 'http://lexvo.org/id/iso639-3/nob').
language0(nog, 'http://lexvo.org/id/iso639-3/nog').
language0(non, 'http://lexvo.org/id/iso639-3/non').
language0(nor, 'http://lexvo.org/id/iso639-3/nor').
language0(nqo, 'http://lexvo.org/id/iso639-3/nqo').
language0(nso, 'http://lexvo.org/id/iso639-3/nso').
language0(nub, 'http://lexvo.org/id/iso639-5/nub').
language0(nwc, 'http://lexvo.org/id/iso639-3/nwc').
language0(nya, 'http://lexvo.org/id/iso639-3/nya').
language0(nym, 'http://lexvo.org/id/iso639-3/nym').
language0(nyn, 'http://lexvo.org/id/iso639-3/nyn').
language0(nyo, 'http://lexvo.org/id/iso639-3/nyo').
language0(nzi, 'http://lexvo.org/id/iso639-3/nzi').
language0(oci, 'http://lexvo.org/id/iso639-3/oci').
language0(oji, 'http://lexvo.org/id/iso639-3/oji').
language0(ori, 'http://lexvo.org/id/iso639-3/ori').
language0(orm, 'http://lexvo.org/id/iso639-3/orm').
language0(osa, 'http://lexvo.org/id/iso639-3/osa').
language0(oss, 'http://lexvo.org/id/iso639-3/oss').
language0(ota, 'http://lexvo.org/id/iso639-3/ota').
language0(oto, 'http://lexvo.org/id/iso639-5/oto').
language0(paa, 'http://lexvo.org/id/iso639-5/paa').
language0(pag, 'http://lexvo.org/id/iso639-3/pag').
language0(pal, 'http://lexvo.org/id/iso639-3/pal').
language0(pam, 'http://lexvo.org/id/iso639-3/pam').
language0(pan, 'http://lexvo.org/id/iso639-3/pan').
language0(pap, 'http://lexvo.org/id/iso639-3/pap').
language0(pau, 'http://lexvo.org/id/iso639-3/pau').
language0(peo, 'http://lexvo.org/id/iso639-3/peo').
language0(per, 'http://lexvo.org/id/iso639-3/fas').
language0(phi, 'http://lexvo.org/id/iso639-5/phi').
language0(phn, 'http://lexvo.org/id/iso639-3/phn').
language0(pli, 'http://lexvo.org/id/iso639-3/pli').
language0(pol, 'http://lexvo.org/id/iso639-3/pol').
language0(pon, 'http://lexvo.org/id/iso639-3/pon').
language0(por, 'http://lexvo.org/id/iso639-3/por').
language0(pra, 'http://lexvo.org/id/iso639-5/pra').
language0(pro, 'http://lexvo.org/id/iso639-3/pro').
language0(pus, 'http://lexvo.org/id/iso639-3/pus').
language0(que, 'http://lexvo.org/id/iso639-3/que').
language0(raj, 'http://lexvo.org/id/iso639-3/raj').
language0(rap, 'http://lexvo.org/id/iso639-3/rap').
language0(rar, 'http://lexvo.org/id/iso639-3/rar').
language0(roa, 'http://lexvo.org/id/iso639-5/roa').
language0(roh, 'http://lexvo.org/id/iso639-3/roh').
language0(rom, 'http://lexvo.org/id/iso639-3/rom').
language0(ron, 'http://lexvo.org/id/iso639-3/ron').
language0(rum, 'http://lexvo.org/id/iso639-3/ron').
language0(run, 'http://lexvo.org/id/iso639-3/run').
language0(rup, 'http://lexvo.org/id/iso639-3/rup').
language0(rus, 'http://lexvo.org/id/iso639-3/rus').
language0(sad, 'http://lexvo.org/id/iso639-3/sad').
language0(sag, 'http://lexvo.org/id/iso639-3/sag').
language0(sah, 'http://lexvo.org/id/iso639-3/sah').
language0(sai, 'http://lexvo.org/id/iso639-5/sai').
language0(sal, 'http://lexvo.org/id/iso639-5/sal').
language0(sam, 'http://lexvo.org/id/iso639-3/sam').
language0(san, 'http://lexvo.org/id/iso639-3/san').
language0(sas, 'http://lexvo.org/id/iso639-3/sas').
language0(sat, 'http://lexvo.org/id/iso639-3/sat').
language0(scn, 'http://lexvo.org/id/iso639-3/scn').
language0(sco, 'http://lexvo.org/id/iso639-3/sco').
language0(sel, 'http://lexvo.org/id/iso639-3/sel').
language0(sem, 'http://lexvo.org/id/iso639-5/sem').
language0(sga, 'http://lexvo.org/id/iso639-3/sga').
language0(sgn, 'http://lexvo.org/id/iso639-5/sgn').
language0(shn, 'http://lexvo.org/id/iso639-3/shn').
language0(sid, 'http://lexvo.org/id/iso639-3/sid').
language0(sin, 'http://lexvo.org/id/iso639-3/sin').
language0(sio, 'http://lexvo.org/id/iso639-5/sio').
language0(sit, 'http://lexvo.org/id/iso639-5/sit').
language0(sla, 'http://lexvo.org/id/iso639-5/sla').
language0(slk, 'http://lexvo.org/id/iso639-3/slk').
language0(slo, 'http://lexvo.org/id/iso639-3/slk').
language0(slv, 'http://lexvo.org/id/iso639-3/slv').
language0(sma, 'http://lexvo.org/id/iso639-3/sma').
language0(sme, 'http://lexvo.org/id/iso639-3/sme').
language0(smi, 'http://lexvo.org/id/iso639-5/smi').
language0(smj, 'http://lexvo.org/id/iso639-3/smj').
language0(smn, 'http://lexvo.org/id/iso639-3/smn').
language0(smo, 'http://lexvo.org/id/iso639-3/smo').
language0(sms, 'http://lexvo.org/id/iso639-3/sms').
language0(sna, 'http://lexvo.org/id/iso639-3/sna').
language0(snd, 'http://lexvo.org/id/iso639-3/snd').
language0(snk, 'http://lexvo.org/id/iso639-3/snk').
language0(sog, 'http://lexvo.org/id/iso639-3/sog').
language0(som, 'http://lexvo.org/id/iso639-3/som').
language0(son, 'http://lexvo.org/id/iso639-5/son').
language0(sot, 'http://lexvo.org/id/iso639-3/sot').
language0(spa, 'http://lexvo.org/id/iso639-3/spa').
language0(sqi, 'http://lexvo.org/id/iso639-3/sqi').
language0(srd, 'http://lexvo.org/id/iso639-3/srd').
language0(srn, 'http://lexvo.org/id/iso639-3/srn').
language0(srp, 'http://lexvo.org/id/iso639-3/srp').
language0(srr, 'http://lexvo.org/id/iso639-3/srr').
language0(ssa, 'http://lexvo.org/id/iso639-5/ssa').
language0(ssw, 'http://lexvo.org/id/iso639-3/ssw').
language0(suk, 'http://lexvo.org/id/iso639-3/suk').
language0(sun, 'http://lexvo.org/id/iso639-3/sun').
language0(sus, 'http://lexvo.org/id/iso639-3/sus').
language0(sux, 'http://lexvo.org/id/iso639-3/sux').
language0(swa, 'http://lexvo.org/id/iso639-3/swa').
language0(swe, 'http://lexvo.org/id/iso639-3/swe').
language0(syc, 'http://lexvo.org/id/iso639-3/syc').
language0(syr, 'http://lexvo.org/id/iso639-3/syr').
language0(tah, 'http://lexvo.org/id/iso639-3/tah').
language0(tai, 'http://lexvo.org/id/iso639-5/tai').
language0(tam, 'http://lexvo.org/id/iso639-3/tam').
language0(tat, 'http://lexvo.org/id/iso639-3/tat').
language0(tel, 'http://lexvo.org/id/iso639-3/tel').
language0(tem, 'http://lexvo.org/id/iso639-3/tem').
language0(ter, 'http://lexvo.org/id/iso639-3/ter').
language0(tet, 'http://lexvo.org/id/iso639-3/tet').
language0(tgk, 'http://lexvo.org/id/iso639-3/tgk').
language0(tgl, 'http://lexvo.org/id/iso639-3/tgl').
language0(tha, 'http://lexvo.org/id/iso639-3/tha').
language0(tib, 'http://lexvo.org/id/iso639-3/bod').
language0(tig, 'http://lexvo.org/id/iso639-3/tig').
language0(tir, 'http://lexvo.org/id/iso639-3/tir').
language0(tiv, 'http://lexvo.org/id/iso639-3/tiv').
language0(tkl, 'http://lexvo.org/id/iso639-3/tkl').
language0(tlh, 'http://lexvo.org/id/iso639-3/tlh').
language0(tli, 'http://lexvo.org/id/iso639-3/tli').
language0(tmh, 'http://lexvo.org/id/iso639-3/tmh').
language0(tog, 'http://lexvo.org/id/iso639-3/tog').
language0(ton, 'http://lexvo.org/id/iso639-3/ton').
language0(tpi, 'http://lexvo.org/id/iso639-3/tpi').
language0(tsi, 'http://lexvo.org/id/iso639-3/tsi').
language0(tsn, 'http://lexvo.org/id/iso639-3/tsn').
language0(tso, 'http://lexvo.org/id/iso639-3/tso').
language0(tuk, 'http://lexvo.org/id/iso639-3/tuk').
language0(tum, 'http://lexvo.org/id/iso639-3/tum').
language0(tup, 'http://lexvo.org/id/iso639-5/tup').
language0(tur, 'http://lexvo.org/id/iso639-3/tur').
language0(tut, 'http://lexvo.org/id/iso639-5/tut').
language0(tvl, 'http://lexvo.org/id/iso639-3/tvl').
language0(twi, 'http://lexvo.org/id/iso639-3/twi').
language0(tyv, 'http://lexvo.org/id/iso639-3/tyv').
language0(udm, 'http://lexvo.org/id/iso639-3/udm').
language0(uga, 'http://lexvo.org/id/iso639-3/uga').
language0(uig, 'http://lexvo.org/id/iso639-3/uig').
language0(ukr, 'http://lexvo.org/id/iso639-3/ukr').
language0(umb, 'http://lexvo.org/id/iso639-3/umb').
language0(und, 'http://lexvo.org/id/iso639-3/und').
language0(urd, 'http://lexvo.org/id/iso639-3/urd').
language0(uzb, 'http://lexvo.org/id/iso639-3/uzb').
language0(vai, 'http://lexvo.org/id/iso639-3/vai').
language0(ven, 'http://lexvo.org/id/iso639-3/ven').
language0(vie, 'http://lexvo.org/id/iso639-3/vie').
language0(vol, 'http://lexvo.org/id/iso639-3/vol').
language0(vot, 'http://lexvo.org/id/iso639-3/vot').
language0(wak, 'http://lexvo.org/id/iso639-5/wak').
language0(wal, 'http://lexvo.org/id/iso639-3/wal').
language0(war, 'http://lexvo.org/id/iso639-3/war').
language0(was, 'http://lexvo.org/id/iso639-3/was').
language0(wel, 'http://lexvo.org/id/iso639-3/cym').
language0(wen, 'http://lexvo.org/id/iso639-5/wen').
language0(wln, 'http://lexvo.org/id/iso639-3/wln').
language0(wol, 'http://lexvo.org/id/iso639-3/wol').
language0(xal, 'http://lexvo.org/id/iso639-3/xal').
language0(xho, 'http://lexvo.org/id/iso639-3/xho').
language0(yao, 'http://lexvo.org/id/iso639-3/yao').
language0(yap, 'http://lexvo.org/id/iso639-3/yap').
language0(yid, 'http://lexvo.org/id/iso639-3/yid').
language0(yor, 'http://lexvo.org/id/iso639-3/yor').
language0(ypk, 'http://lexvo.org/id/iso639-5/ypk').
language0(zap, 'http://lexvo.org/id/iso639-3/zap').
language0(zbl, 'http://lexvo.org/id/iso639-3/zbl').
language0(zen, 'http://lexvo.org/id/iso639-3/zen').
language0(zha, 'http://lexvo.org/id/iso639-3/zha').
language0(zho, 'http://lexvo.org/id/iso639-3/zho').
language0(znd, 'http://lexvo.org/id/iso639-5/znd').
language0(zul, 'http://lexvo.org/id/iso639-3/zul').
language0(zun, 'http://lexvo.org/id/iso639-3/zun').
language0(zza, 'http://lexvo.org/id/iso639-3/zza').

